### ISSUE TITLE
Update eqeqeq eslint rule

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/eslint-config-pixiebrix#104]
- https://eslint.org/docs/latest/rules/eqeqeq
- Set the "null" option to "never" to enforce using loose equality checks for null
  - Loose checks for `null` will also catch `undefined`

Implementation Sketch
---

- [ ] Switch from `smart` to `always`
- [ ] Add the optional `{ null: "never" }` second afgument
- [ ] Open/merge PR
- [ ] Use the `Publish` workflow to publish a new `patch` version of the repo
- [ ] Install the latest version in the Extension project
- [ ] Run the linter and fix any issues it finds

**Comment by fregante** [comment]
Isn't it here already?

https://github.com/pixiebrix/eslint-config-pixiebrix/blob/4361acf166e102a124d8d7785de02d15d09bc084/index.js#L207-L208

**Comment by twschiller** [comment]
> Isn't it here already?

We want the linter to force us to leave a comment when using `=== null` or `=== undefined` because we should generally never do that. IIRC, the current rule for smart just means it allows `== null` or `== undefined` but doesn't enforce using `==` for detecting nulling values

**Comment by grahamlangford** [comment]
@fungairino GitHub isn't allowing me to assign this issue to you. Probably because you've not worked or commented in this project before. Testing to see if this callout lets me assign you.

**Comment by grahamlangford** [comment]
>@fungairino GitHub isn't allowing me to assign this issue to you. Probably because you've not worked or commented in this project before. Testing to see if this callout lets me assign you.

It did.
