### ISSUE TITLE
Add eslint-plugin-no-only-tests

### ISSUE THREAD

**Issue by johnnymetz** [pixiebrix/eslint-config-pixiebrix#109]
**Background**

During Cypress development, we use `it.only()` to run a single test. See Cypress docs here: https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Excluding-and-Including-Tests

I occasionally forget to remove `.only()` after developing a single test. Would be nice if eslint catches this mistake. Looks like there's an eslint plugin for it: https://github.com/levibuzolic/eslint-plugin-no-only-tests

**Comment by fregante** [comment]
It's part of the jest plugin and it's enabled now 🙌 

https://github.com/jest-community/eslint-plugin-jest/blob/HEAD/docs/rules/no-focused-tests.md
