### ISSUE TITLE
Enable `no-non-null-assertion` (?)

### ISSUE THREAD

**Issue by fregante** [pixiebrix/eslint-config-pixiebrix#115]
Graham mentioned this rule in a review in https://github.com/pixiebrix/pixiebrix-extension/pull/6534, I thought I'd open an issue here to discuss it and potentially add it to this config.

https://typescript-eslint.io/rules/no-non-null-assertion

I'm not entirely sure we should enable it. It's ideal in theory, but very often code guarantees that a value is not null in a way that TypeScript can't verify. Or maybe the types are just too broad (e.g. we know `paragraphEl.textContent` exists but its type is `string | undefined`)

In that case we have 3 options:

- add a condition, e.g. `if (!x), return` or `throw`, writing code that will never be run
- use `?.`, pushing the non-existent null down the line
- use `!`, silence the rule, write explanation

All of these make the code more verbose for non-existent benefit. Maybe the last one works as documentation, but it's still noisy and a cause of additional time spent on an unimportant piece of code.

cc @grahamlangford @mnholtz

**Comment by grahamlangford** [comment]
There's an additional benefit to having to silence the rule -- calling extra attention to that code during PRs. 

Enabling the rule encourages engineers to be more careful with the usage.

**Comment by mnholtz** [comment]
I agree with @grahamlangford and would be on board with approach 3. Additionally, I hardly see this pattern at all (although maybe we'll see it more often during our migration to `strictNullChecks`).

**Comment by fregante** [comment]
Done in #121 

https://github.com/pixiebrix/eslint-config-pixiebrix/blob/323f4e13029755f56bf57e10bfe1cf5059066d10/index.js#L135
