### ISSUE TITLE
Add no-use-before-define

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/eslint-config-pixiebrix#56]
Implement the `no-use-before-define` ESLint [rule](https://eslint.org/docs/latest/rules/no-use-before-define)

**Comment by fregante** [comment]
We got it now

- https://github.com/pixiebrix/eslint-config-pixiebrix/pull/57

https://github.com/pixiebrix/eslint-config-pixiebrix/blob/3edeadabe89673e07b925caf87d46019268a399f/index.js#L264
