### ISSUE TITLE
Restrict imports of classnames to cx

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/eslint-config-pixiebrix#64]
## Motivation
* We want to enforce our convention of prefering `import cx from 'classnames'` over `import classnames from 'classnames'`

## Acceptance Criteria
* Find an existing linting rule that would allow us to enforce this
_**OR**_
* Create our own custom linting rule

## Notes
* [ESLint Plugin Import](https://www.npmjs.com/package/eslint-plugin-import) has a draft PR to provide a rule that would support this
* The draft PR can be found [here](https://github.com/import-js/eslint-plugin-import/pull/1143)

**Comment by fregante** [comment]
This can be done via `no-restricted-imports`. I'll add it after this is merged:

- #228
