### ISSUE TITLE
Enable "No Explicit Any" Linting Rule

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/eslint-config-pixiebrix#73]
- https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-explicit-any.md

**Comment by fregante** [comment]
We already have this enabled as a warning so some usage has already been fixed or whitelisted. I noticed that there are only ~50 issues, many grouped into vendor-ish files that we can exclude.

Feel free to assign it to me

**Comment by grahamlangford** [comment]
> We already have this enabled as a warning so some usage has already been fixed or whitelisted. I noticed that there are only ~50 issues, many grouped into vendor-ish files that we can exclude.
> 
> Feel free to assign it to me

That's great news! It's far fewer than I expected. I would've thought it would end up being a similar lift to strictNullChecks.

**Comment by fregante** [comment]
> it would end up being a similar lift to strictNullChecks

This specific rule isn't too difficult, but it doesn't eliminate `any` from the codebase. Unfortunately `any` is _viral_, so if any operation introduces it, it creates a domino effect. TypeScript doesn't even try to defend against this since `any` specifically silences type errors 🤷‍♂️ 

There are a handful of rules named `@typescript-eslint/no-unsafe-*` that catch implicit `any`, but they cause 779 lint errors at the moment.

**Comment by grahamlangford** [comment]
> > it would end up being a similar lift to strictNullChecks
> 
> This specific rule isn't too difficult, but it doesn't eliminate `any` from the codebase. Unfortunately `any` is _viral_, so if any operation introduces it, it creates a domino effect. TypeScript doesn't even try to defend against this since `any` specifically silences type errors 🤷‍♂️
> 
> There are a handful of rules named `@typescript-eslint/no-unsafe-*` that catch implicit `any`, but they cause 779 lint errors at the moment.

Noted. I'm marking down in my notes to look into adopting those rules in the future then.

**Comment by grahamlangford** [comment]
I just tested with `no-unsafe-argument` and that passes in Extension with 0 errors.

**Comment by fregante** [comment]
I think that rule is already enabled in the extension, I'm talking about these 4 more:

https://github.com/pixiebrix/eslint-config-pixiebrix/blob/888f2a4ba411dd65063db0250b366f4d41e3a15c/index.js#L237-L240

**Comment by grahamlangford** [comment]
Yes, I tested those. They'll definitely need their own issues. We'll worry about them later on. They're probably good candidates to start off as warnings.

**Comment by fregante** [comment]
Fixed by https://github.com/pixiebrix/eslint-config-pixiebrix/pull/129
